# Numpy

Numpy is a library to compute and decompose Matrix. 

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

- a powerful N-dimensional array object

- sophisticated (broadcasting) functions

- tools for integrating C/C++ and Fortran code

- useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

### Example of a matrix is: 

![](../images/numpy.gif)

We see a photo as a memory, as a picture or a piece of imformation. But how computer sees it is like an array or a matrix in an n-dimensional vector space. Where each pixel denotes an element in a matrix arranged in rows and columns. 

In [1]:
import numpy as np

# Data Types in Numpy

- Data types
- Array types
- Type conversions
- Array creation
- Indexing
- Slicing
- Shape manipulation

NumPy has a multi-dimensional array object called ndarray.It consists of two parts:

1. The actual data
2. Some metadata describing the data


The NumPy array is homogeneous—the items in the array have to be of the same type. The advantage is that, if we know that the items in the array are of the same type, then it is easy to determine the storage size required for the array. 

In [2]:
a = np.array([1,2,3,4,5])
a.dtype

dtype('int64')

In [3]:
a #the vector has five elements

array([1, 2, 3, 4, 5])

# Creating a Multidimensional Array

In [7]:
b = np.array([[1,2],
             [3,4]])

In [8]:
b

array([[1, 2],
       [3, 4]])

In [9]:
'''inorder to know the number of rows and columns present in the matrix we use shape. The output is displayed in
terms of Rows and Columns'''

b.shape

(2, 2)

The array function creates an array from an object that you give to it. The object needs to be array-like, for instance, a Python list.

In [12]:
#create a 3-dim and a 4-dim array

# Selecting elements

In [13]:
b

array([[1, 2],
       [3, 4]])

You enter the first list with an index followed by the index of the elements 

In [19]:
print(b[0][0])
print(b[0][1])
print(b[0])
print(b[1][0])
print(b[1][1])
print(b[1])

1
2
[1 2]
3
4
[3 4]


# NumPy numerical types

Python has an integer type, a float type, and a complex type, however, this is not enough for scientific computing and, for this reason, NumPy has a lot more data types. In practice, we need even more types with varying precision and, therefore, different memory size of the type. The majority of the NumPy numerical types end with a number. This number indicates the number of bits associated with the type. The following table (adapted from the NumPy user guide) gives an overview of NumPy numerical types:

| Type | Description | 
| --- | --- | 
|<b> bool </b>| Boolean (True or False) stored as a bit |
|<b> inti </b>| Platform integer (normally either int32 or int64) | 
|<b> int8 </b>| Byte (-128 to 127) | 
|<b> int16 </b>| Integer (-32768 to 32767) | 
|<b> int32 </b>| Integer (-2 ** 31 to 2 ** 31 -1) | 
|<b> int64 </b>| Integer (-2 ** 63 to 2 ** 63 -1) | 
|<b> uint8 </b>| Unsigned integer (0 to 255) | 
|<b> uint16 </b>| Unsigned integer (0 to 65535) | 
|<b> uint32 </b>| Unsigned integer (0 to 2 ** 32 - 1) | 
|<b> uint64 </b>| Unsigned integer (0 to 2 ** 64 - 1) | 
|<b> float16 </b>| Half precision float: sign bit, 5 bits exponent, 10 bits mantissa | 
|<b> float32 </b>| Single precision float: sign bit, 8 bits exponent, 23 bits mantissa | 
|<b> float64 or float </b>| Double precision float: sign bit, 11 bits exponent, 52 bits mantissa | 
|<b> complex64 </b>| Complex number, represented by two 32-bit floats (real and imaginary components)|
|<b> complex128 or complex </b>|Complex number, represented by two 64-bit floats (real and imaginary components)


# Stacking

Arrays can be stacked horizontally, depth-wise, or vertically. We can use, for that purpose, the vstack, dstack, hstack, column_stack, row_stack, and concatenate functions.

In [28]:
np.arange(9).reshape(3,3)

#Make sure that the multiple of the rows and columns are equal to the elements present

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Types of Stacking

 - Horizontal Stacking
 - Vertical Stacking
 - Depth Stacking
 - Column Stacking
 - Row Stacking

In [30]:
#Horizontal Stacking

np.hstack((a, a)) #if you're having more than two matrix to stack make sure you use two pairs of parenthesis

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [32]:
#Vertical Stacking

np.vstack((a,a))

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [34]:
#Depth Stacking 
"""Additionally, there is the depth-wise stacking using dstack and a tuple, of course. 
    This means stacking of a list of arrays along the third axis (depth). 
    For instance, we could stack 2D arrays of image data on top of each other."""

np.dstack((a, a))

array([[[1, 1],
        [2, 2],
        [3, 3],
        [4, 4],
        [5, 5]]])

In [37]:
#Column Stacking

np.column_stack((a,a,a))

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5]])

In [38]:
#Row stacking
np.row_stack((a, a))

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

# Splitting

Arrays can be split vertically, horizontally, or depth wise. The functions involved are hsplit, vsplit, dsplit, and split. We can either split into arrays of the same shape or indicate the position after which the split should occur.

Types of Splitting

1. Vertically
2. Horizontally
3. Depth Split

In [41]:
"""Horizontal splitting: 
The ensuing code splits an array along its horizontal axis into three pieces of the same size and shape"""

print(a)
np.hsplit(np.array([1,2,3,4]), 2)

[1 2 3 4 5]


[array([1, 2]), array([3, 4])]

In [45]:
"""Vertical splitting: vsplit splits along the vertical axis"""

np.vsplit(np.array([[1,2,3,4],[1,2,3,4]]), 2)

#it works with two or more columns

[array([[1, 2, 3, 4]]), array([[1, 2, 3, 4]])]

In [47]:
"""Depth-wise splitting: The dsplit function, unsurprisingly, splits depth-wise."""

c = np.arange(27).reshape(3, 3, 3)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [48]:
np.dsplit(c,3)

[array([[[ 0],
         [ 3],
         [ 6]],
 
        [[ 9],
         [12],
         [15]],
 
        [[18],
         [21],
         [24]]]), array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]), array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]])]